### PR TITLE
Added a convergence study for Hertz benchmark case

### PR DESCRIPTION
**Pull request by MarkoLeskovar**
Dear Andreas,

I finished with the convergence study. Each number next to gid input files represents an element size (_07 -> 0.7 m). You can add any new mesh configuration, just watch out that they follow the sequential numbering.

I tried to push the changes but then I realised that I cannot push directly to master, so I created a new brach and push to this one. Sorry if I caused any incovenience. 

Best regards,
Marko Leskovar

### CODE REVIEW

**Comment by andreas-apostolatos** [comment]
> Dear Andreas,
> 
> I finished with the convergence study. Each number next to gid input files represents an element size (_07 -> 0.7 m). You can add any new mesh configuration, just watch out that they follow the sequential numbering.
> 
> I tried to push the changes but then I realised that I cannot push directly to master, so I created a new brach and push to this one. Sorry if I caused any incovenience.
> 
> Best regards,
> Marko Leskovar

Hello Marko,

thank you very much for the nice addition. 

I notice that the results deviate from the expected solution, is that due to the high load applied in this case? Moreover, when I try to change the applied traction load the code crashes, do you have any idea why?

It would be excellent if you could review the literature regarding the Herzian contact case because I feel that we are missing something.

Thanks again!
Andreas

**Comment by MarkoLeskovar** [comment]
Dear Andreas,

if the load is too small there is only one contact node and no distance to compute. The code crashes at the function that computes resultants.

Regarding the results. It's hard to judge the results since this analytical function was already implemented by Fabian. I already took a look at the theory, but could not find something that would match our case exactly (rigid boundary, deformable body, 2D case-cylinder, no friction). I can investige further and see what is missing.

Best regards,
Marko Leskovar

**Comment by MarkoLeskovar** [comment]
Dear Andreas,

I refined the mesh and applied lower load. This is more suitable and in the range of linear theory for which the Hertz contact mechanics is valid. The only differences remain to be in the contact length, but they deviate by the size of the element in contact.

Best regards,
Marko Leskovar

**Comment by andreas-apostolatos** [comment]
> Dear Andreas,
> 
> I finished with the convergence study. Each number next to gid input files represents an element size (_07 -> 0.7 m). You can add any new mesh configuration, just watch out that they follow the sequential numbering.
> 
> I tried to push the changes but then I realised that I cannot push directly to master, so I created a new brach and push to this one. Sorry if I caused any incovenience.
> 
> Best regards,
> Marko Leskovar

Hallo Marko,

the new meshes with the refinement at the contact area and lowering the load seems to be fixing the problem. I guess that the benchmark requires linearity and thus small displacements, can you please confirm that from the theory I provided you with?

However, I would like to ask you to change the meshes and have the corresponding refinement towards the contact area to grow gradually, so that we don't have such big differences between neighbouring elements. Can you please do that for all the mesh levels?

Greetings,
Andreas

**Pull request merged**
