### PR TITLE
Signorini contact problem

### PR DESCRIPTION
**Pull request by MarkoLeskovar**
Dear Andreas,

I finished the Signorini contact problem. There are currently two example cases currently inside the main file. The only thing we should add is that Hertz contact benchmark, but for that we need to discuss the topic a bit more in detail.

Best regards,
Marko Leskovar

### CODE REVIEW

**Comment by andreas-apostolatos** [comment]
> Dear Andreas,
> 
> I finished the Signorini contact problem. There are currently two example cases currently inside the main file. The only thing we should add is that Hertz contact benchmark, but for that we need to discuss the topic a bit more in detail.
> 
> Best regards,
> Marko Leskovar

Hello Marko,

thanks for taking care of this. Your developments look quite nice. 

However, I tried to increase the amplitude of the external load and it seems that the contact constraints are not appropriately satisfied. Can you please take a look?

Greetings,
Andreas

**Comment by MarkoLeskovar** [comment]
> 
> 
> > Dear Andreas,
> > I finished the Signorini contact problem. There are currently two example cases currently inside the main file. The only thing we should add is that Hertz contact benchmark, but for that we need to discuss the topic a bit more in detail.
> > Best regards,
> > Marko Leskovar
> 
> Hello Marko,
> 
> thanks for taking care of this. Your developments look quite nice.
> 
> However, I tried to increase the amplitude of the external load and it seems that the contact constraints are not appropriately satisfied. Can you please take a look?
> 
> Greetings,
> Andreas

If you increase the load too much the intial deformations get too large and whole problem is not a linear problem anymore. Gap functions are assumed linear and therefore probably don't work correctly. Remember that the first step of calculation is without any contact nodes. I think this is not a trivial problem to solve and if we really want to solve it, we should change the the whole approach how the gap functions are calculated and how the load is applied.

Best regards,
Marko Leskovar

**Comment by andreas-apostolatos** [comment]
> > > Dear Andreas,
> > > I finished the Signorini contact problem. There are currently two example cases currently inside the main file. The only thing we should add is that Hertz contact benchmark, but for that we need to discuss the topic a bit more in detail.
> > > Best regards,
> > > Marko Leskovar
> > 
> > 
> > Hello Marko,
> > thanks for taking care of this. Your developments look quite nice.
> > However, I tried to increase the amplitude of the external load and it seems that the contact constraints are not appropriately satisfied. Can you please take a look?
> > Greetings,
> > Andreas
> 
> If you increase the load too much the intial deformations get too large and whole problem is not a linear problem anymore. Gap functions are assumed linear and therefore probably don't work correctly. Remember that the first step of calculation is without any contact nodes. I think this is not a trivial problem to solve and if we really want to solve it, we should change the the whole approach how the gap functions are calculated and how the load is applied.
> 
> Best regards,
> Marko Leskovar

I am not sure is there problem is induced by the geometrical nonlinearity of the problem. I actually could run the original code and it does not produce these artifacts. Please drop by anytime to discuss on this issue.

Greetings,
Andreas

**Comment by andreas-apostolatos** [comment]
Hello Marko,

thank you very much for the changes you added recently.

I checked the main_ driver script and the example 'example_01_bridge' still produces unexpected results. Did you find some time to look what is the problem there?

Have a nice evening,
Andreas

**Comment by MarkoLeskovar** [comment]
Dear Andreas,

The bug is now fixed. The code produces nice results and it's easier to read. I just focused on the “solveSignoriniLagrange_1” solver since it's easier to understand. The second one doesn't work yet and needs small adjustments. I would even completely delete the second solver and just keep the first one, since it's more straight forward.

Can you take a detailed look at the code and let me know what do you think? Meanwhile I will start writing detailed documentation on how the code works. 

Could we also meet on Monday?

Best regards,
Marko Leskovar

**Comment by andreas-apostolatos** [comment]
> Dear Andreas,
> 
> The bug is now fixed. The code produces nice results and it's easier to read. I just focused on the “solveSignoriniLagrange_1” solver since it's easier to understand. The second one doesn't work yet and needs small adjustments. I would even completely delete the second solver and just keep the first one, since it's more straight forward.
> 
> Can you take a detailed look at the code and let me know what do you think? Meanwhile I will start writing detailed documentation on how the code works.
> 
> Could we also meet on Monday?
> 
> Best regards,
> Marko Leskovar

Dear Marko,

that's really great. I just had a look and I am very happy with the changes you made. Yes, please go ahead with the documentation. I have time today until 12:00 and tomorrow. However, from Wednesday until Thursday I am completely blocked and I then have time again on Friday.

Thanks a lot for the great job and looking forward discussing the next steps.

Greetings,
Andreas

**Comment by MarkoLeskovar** [comment]
Then I will prepare the documentation and drop by on Friday morning. 

Greetings,
Marko Leskovar

**Comment by andreas-apostolatos** [comment]
> Then I will prepare the documentation and drop by on Friday morning.
> 
> Greetings,
> Marko Leskovar

Sounds great.

See you,
Andreas

**Review by andreas-apostolatos — APPROVED** [review]

**Pull request merged**
